import React from "react";
import { Check, PackageSearch, Plus, Search, ShieldCheck, Store, X } from "lucide-react";
import { jsonOku } from "../../shared/json";
type Profil={id:number;unvan:string;kategoriler:string;sehir:string;aciklama:string;dogrulandi:boolean;yayinda?:boolean};
type Talep={id:number;baslik:string;kategori:string;urunHizmet:string;miktar:number;birim:string;teslimatSehri:string;sonTeklifAt:string;aciklama:string;durum?:string;teklifSayisi?:number;teklifVerildi?:boolean};
type Teklif={id:number;talepId:number;talepBasligi:string;birimFiyat:number;paraBirimi:string;terminGun:number;minimumSiparis:number;not:string;durum:string;tedarikciUnvani:string};
type Ekran={profiller:Profil[];talepler:Talep[];acikTalepler:Talep[];gelenTeklifler:Teklif[];profil:Profil|null};
const initial={profil:{unvan:"",kategoriler:"",sehir:"",aciklama:"",yayinda:true},talep:{baslik:"",kategori:"",urunHizmet:"",miktar:"",birim:"Adet",teslimatSehri:"",sonTeklifAt:"",aciklama:""},teklif:{birimFiyat:"",paraBirimi:"TRY",terminGun:"",minimumSiparis:"",not:""}};
export function TedarikciPazaryeriSayfasi(){
 const [data,setData]=React.useState<Ekran|null>(null),[tab,setTab]=React.useState("suppliers"),[modal,setModal]=React.useState(""),[selected,setSelected]=React.useState<Talep|null>(null),[query,setQuery]=React.useState(""),[form,setForm]=React.useState(initial),[message,setMessage]=React.useState(""),[error,setError]=React.useState("");
 const load=React.useCallback(()=>jsonOku<Ekran>("/api/ekran/tedarikci-pazaryeri").then(d=>{setData(d);if(d.profil)setForm(f=>({...f,profil:{unvan:d.profil!.unvan,kategoriler:d.profil!.kategoriler,sehir:d.profil!.sehir,aciklama:d.profil!.aciklama,yayinda:!!d.profil!.yayinda}}));}).catch((e:Error)=>setError(e.message)),[]);
 React.useEffect(()=>{document.title="Tedarikçi Pazaryeri | Systemcel";load();},[load]);
 async function send(url:string,body?:unknown){try{setError("");const r=await jsonOku<{mesaj:string}>(url,{method:url.endsWith("profil")?"PUT":"POST",body:body?JSON.stringify(body):undefined});setMessage(r.mesaj);setModal("");await load();}catch(e){setError(e instanceof Error?e.message:"İşlem başarısız.");}}
 const suppliers=(data?.profiller??[]).filter(x=>(x.unvan+x.kategoriler+x.sehir).toLocaleLowerCase("tr").includes(query.toLocaleLowerCase("tr")));
 const set=(group:keyof typeof initial,key:string,value:string|boolean)=>setForm(f=>({...f,[group]:{...f[group],[key]:value}}));
 return <main className="supplier-marketplace"><section className="supplier-marketplace__hero"><div><span className="supplier-marketplace__eyebrow"><Store size={15}/> TEDARİK AĞI</span><h1>Tedarikçiyi bul. Talebi yayınla. Teklifi karşılaştır.</h1><p>Ürün bazlı ihtiyaçlarını yayınla; fiyat, termin ve minimum sipariş koşullarını aynı yerde değerlendir.</p></div><button className="supplier-marketplace__hero-action" onClick={()=>setModal("talep")}><Plus/>Alım talebi oluştur</button></section>
 <nav className="supplier-marketplace__tabs"><button className={tab==="suppliers"?"active":""} onClick={()=>setTab("suppliers")}>Tedarikçiler</button><button className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}>Açık talepler</button><button className={tab==="offers"?"active":""} onClick={()=>setTab("offers")}>Tekliflerim</button><button onClick={()=>setModal("profil")}><Store size={16}/>Tedarikçi profilim</button></nav>
 {message?<p className="supplier-marketplace__notice"><Check/>{message}</p>:null}{error?<p className="supplier-marketplace__error">{error}</p>:null}
 {tab==="suppliers"?<><section className="supplier-marketplace__search"><Search/><input aria-label="Tedarikçi ara" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Şirket, kategori veya şehir ara"/></section><section className="supplier-marketplace__cards">{suppliers.map(p=><article key={p.id}><span className="supplier-marketplace__avatar">{p.unvan.slice(0,2).toUpperCase()}</span><div><h3>{p.unvan}{p.dogrulandi?<ShieldCheck size={16}/>:null}</h3><p>{p.kategoriler} · {p.sehir}</p><small>{p.aciklama}</small></div></article>)}{data&&suppliers.length===0?<Empty text="Yayında tedarikçi yok."/>:null}</section></>:null}
 {tab==="requests"?<section className="supplier-marketplace__request-grid">{(data?.acikTalepler??[]).map(t=><article key={t.id}><small>{t.kategori} · {t.teslimatSehri}</small><h3>{t.baslik}</h3><p>{t.urunHizmet}</p><strong>{t.miktar} {t.birim}</strong><span>{new Date(t.sonTeklifAt).toLocaleDateString("tr-TR")} tarihine kadar</span><button disabled={t.teklifVerildi} onClick={()=>{setSelected(t);setModal("teklif")}}>{t.teklifVerildi?"Teklif verildi":"Teklif ver"}</button></article>)}</section>:null}
 {tab==="offers"?<section className="supplier-marketplace__offers"><h2>Alım taleplerim</h2>{(data?.talepler??[]).map(t=><article key={t.id}><div><strong>{t.baslik}</strong><span>{t.miktar} {t.birim} · {t.durum}</span></div><b>{t.teklifSayisi} teklif</b></article>)}<h2>Gelen teklifler</h2>{(data?.gelenTeklifler??[]).map(o=><article key={o.id}><div><strong>{o.tedarikciUnvani}</strong><span>{o.talepBasligi} · {o.terminGun} gün · min. {o.minimumSiparis}</span></div><b>{o.birimFiyat} {o.paraBirimi}</b>{o.durum==="Gonderildi"?<button onClick={()=>send(`/api/ekran/tedarikci-pazaryeri/teklifler/${o.id}/kabul`)}>Kabul et</button>:<em>{o.durum}</em>}</article>)}</section>:null}
 {modal?<Modal title={modal==="profil"?"Tedarikçi profilim":modal==="talep"?"Alım talebi oluştur":`${selected?.baslik} için teklif`} close={()=>setModal("")} submit={()=>modal==="profil"?send("/api/ekran/tedarikci-pazaryeri/profil",form.profil):modal==="talep"?send("/api/ekran/tedarikci-pazaryeri/talepler",{...form.talep,miktar:Number(form.talep.miktar)}):send(`/api/ekran/tedarikci-pazaryeri/talepler/${selected?.id}/teklifler`,{...form.teklif,birimFiyat:Number(form.teklif.birimFiyat),terminGun:Number(form.teklif.terminGun),minimumSiparis:Number(form.teklif.minimumSiparis)})}>{modal==="profil"?<><Field l="Unvan" v={form.profil.unvan} s={v=>set("profil","unvan",v)}/><Field l="Kategoriler" v={form.profil.kategoriler} s={v=>set("profil","kategoriler",v)}/><Field l="Şehir" v={form.profil.sehir} s={v=>set("profil","sehir",v)}/><Field l="Tanıtım" v={form.profil.aciklama} s={v=>set("profil","aciklama",v)}/><label><input type="checkbox" checked={form.profil.yayinda} onChange={e=>set("profil","yayinda",e.target.checked)}/>Profili yayınla</label></>:modal==="talep"?<>{(["baslik","kategori","urunHizmet","miktar","birim","teslimatSehri","sonTeklifAt","aciklama"] as const).map(k=><Field key={k} l={({baslik:"Başlık",kategori:"Kategori",urunHizmet:"Ürün veya hizmet",miktar:"Miktar",birim:"Birim",teslimatSehri:"Teslimat şehri",sonTeklifAt:"Son teklif tarihi",aciklama:"Açıklama"})[k]} type={k==="miktar"?"number":k==="sonTeklifAt"?"datetime-local":"text"} v={form.talep[k]} s={v=>set("talep",k,v)}/>)}</>:<>{(["birimFiyat","paraBirimi","terminGun","minimumSiparis","not"] as const).map(k=><Field key={k} l={({birimFiyat:"Birim fiyat",paraBirimi:"Para birimi",terminGun:"Termin (gün)",minimumSiparis:"Minimum sipariş",not:"Teklif notu"})[k]} type={["birimFiyat","terminGun","minimumSiparis"].includes(k)?"number":"text"} v={form.teklif[k]} s={v=>set("teklif",k,v)}/>)}</>}</Modal>:null}</main>}
function Field({l,v,s,type="text"}:{l:string;v:string;s:(v:string)=>void;type?:string}){return <label><span>{l}</span><input required type={type} value={v} onChange={e=>s(e.target.value)}/></label>}
function Modal({title,close,submit,children}:{title:string;close:()=>void;submit:()=>void;children:React.ReactNode}){return <div className="supplier-marketplace__modal" role="dialog" aria-modal="true" aria-label={title}><form onSubmit={e=>{e.preventDefault();submit()}}><button type="button" aria-label="Kapat" onClick={close}><X/></button><h2>{title}</h2>{children}<button className="supplier-marketplace__submit">Kaydet ve yayınla</button></form></div>}
function Empty({text}:{text:string}){return <div className="supplier-marketplace__empty"><PackageSearch/><strong>{text}</strong></div>}
