// <auto-generated />
using System;
using CashTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CashTracker.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(CashTrackerDbContext))]
    [Migration("20260513204444_WebAuthSubscriptionSchema")]
    partial class WebAuthSubscriptionSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashTracker.Core.Entities.Abonelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AylikTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DonemBaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DonemBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DonemSonundaIptal")
                        .HasColumnType("boolean");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IptalAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeSaglayici")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciAbonelikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciMusteriId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("PlanKodu");

                    b.HasIndex("SaglayiciAbonelikId");

                    b.HasIndex("IsletmeId", "Durum");

                    b.ToTable("Abonelik", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.AiKullanimDonemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonemAnahtari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DonemBaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DonemBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("KullanilanMesaj")
                        .HasColumnType("integer");

                    b.Property<int?>("MesajLimiti")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "DonemAnahtari")
                        .IsUnique();

                    b.ToTable("AiKullanimDonemi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSetting", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.BelgeDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BelgeTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId");

                    b.ToTable("BelgeDosya", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.CariHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "CariKartId", "Tarih");

                    b.ToTable("CariHareket", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.CariKart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNoTc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Unvan");

                    b.HasIndex("IsletmeId", "VergiNoTc");

                    b.ToTable("CariKart", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaturaTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("IskontoToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime?>("KesildiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OdenenTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("PortalBelgeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortalUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YerelFaturaNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "CariKartId");

                    b.HasIndex("IsletmeId", "Tarih");

                    b.ToTable("Fatura", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.FaturaSatir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("IskontoOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("IskontoTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("KdvTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("SatirNetTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("SatirToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<bool>("StokEtkilesin")
                        .HasColumnType("boolean");

                    b.Property<int?>("UrunHizmetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId");

                    b.ToTable("FaturaSatir", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.GibPortalAyar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreCipherText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TestModu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId")
                        .IsUnique();

                    b.ToTable("GibPortalAyar", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.GibPortalIslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Basarili")
                        .HasColumnType("boolean");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId", "Tarih");

                    b.ToTable("GibPortalIslemLog", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Isletme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClerkOrganizationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("SahipKullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("TenantTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClerkOrganizationId")
                        .IsUnique();

                    b.HasIndex("IsAktif");

                    b.HasIndex("SahipKullaniciId");

                    b.HasIndex("TenantTipi");

                    b.ToTable("Isletme", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.IsletmeDeneme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeSaglayici")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OdemeYontemiEklendi")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciMusteriId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciOdemeYontemiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "PlanKodu")
                        .IsUnique();

                    b.ToTable("IsletmeDeneme", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.IsletmeEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AiAktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("AiMesajLimiti")
                        .HasColumnType("integer");

                    b.Property<bool>("DonemOtomasyonuAktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("GecerliBaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("GecerliBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GibAktif")
                        .HasColumnType("boolean");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KullaniciLimiti")
                        .HasColumnType("integer");

                    b.Property<bool>("MuhasebeciPaneliAktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("MusteriLimiti")
                        .HasColumnType("integer");

                    b.Property<bool>("MusteriSaglikSkoruAktif")
                        .HasColumnType("boolean");

                    b.Property<bool>("OcrAktif")
                        .HasColumnType("boolean");

                    b.Property<bool>("OneCikmaAktif")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SponsorMuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<bool>("TelegramAktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId")
                        .IsUnique();

                    b.HasIndex("Kaynak");

                    b.HasIndex("PlanKodu");

                    b.HasIndex("SponsorMuhasebeciIsletmeId");

                    b.ToTable("IsletmeEntitlement", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.IsletmeUyelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DavetAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DavetEdenKullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("DavetEposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DavetKodu")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KabulAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DavetKodu")
                        .IsUnique();

                    b.HasIndex("IsletmeId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("IsletmeId", "KullaniciId")
                        .IsUnique();

                    b.ToTable("IsletmeUyelik", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.KalemTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Tip", "Ad")
                        .IsUnique();

                    b.ToTable("KalemTanimi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Kasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GiderTuru")
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kalem")
                        .HasColumnType("text");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Tarih");

                    b.ToTable("Kasa", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonGirisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Eposta");

                    b.HasIndex("HesapTipi");

                    b.HasIndex("AuthProvider", "AuthProviderUserId")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciMusteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DavetKodu")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("MusteriIsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DavetKodu")
                        .IsUnique();

                    b.HasIndex("MuhasebeciIsletmeId");

                    b.HasIndex("MusteriIsletmeId");

                    b.HasIndex("MuhasebeciIsletmeId", "MusteriIsletmeId")
                        .IsUnique();

                    b.ToTable("MuhasebeciMusteri", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UrunHizmetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "UrunHizmetId", "Tarih");

                    b.ToTable("StokHareket", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.TahsilatOdeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("CariHareketId")
                        .HasColumnType("integer");

                    b.Property<int>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<int?>("KasaId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId");

                    b.HasIndex("IsletmeId", "CariKartId", "Tarih");

                    b.ToTable("TahsilatOdeme", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.UrunHizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("KritikStok")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Barkod");

                    b.ToTable("UrunHizmet", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
