// <auto-generated />
using System;
using CashTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CashTracker.Infrastructure.Persistence.Migrations.PostgreSql
{
    [DbContext(typeof(CashTrackerDbContext))]
    partial class CashTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashTracker.Core.Entities.Abonelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AylikTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DonemBaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DonemBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DonemSonundaIptal")
                        .HasColumnType("boolean");

                    b.Property<decimal>("DonemTutari")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EkMusteriKredisi")
                        .HasColumnType("integer");

                    b.Property<string>("FaturalamaDonemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IndirimliDonemKalan")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("IptalAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("KampanyaKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdemeSaglayici")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("OdemeSorunuAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciAbonelikId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciMusteriId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ToleransBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("YenilemeDonemTutari")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("PlanKodu");

                    b.HasIndex("SaglayiciAbonelikId");

                    b.HasIndex("IsletmeId", "Durum");

                    b.ToTable("Abonelik", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.AbonelikOnayi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckoutAnahtari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EkMusteriKredisi")
                        .HasColumnType("integer");

                    b.Property<string>("FaturalamaDonemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("IstemciIpHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KampanyaKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("KdvTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("KullaniciRef")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ListeNetTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("MetinHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetinSurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("NetTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("OnayAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("UserAgentHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("YenilemeNetTutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "CheckoutAnahtari")
                        .IsUnique();

                    b.ToTable("AbonelikOnayi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.AiKullanimDonemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DonemAnahtari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DonemBaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DonemBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("KullanilanMesaj")
                        .HasColumnType("integer");

                    b.Property<int?>("MesajLimiti")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "DonemAnahtari")
                        .IsUnique();

                    b.ToTable("AiKullanimDonemi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.AppSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AppSetting", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.BelgeDosya", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BelgeTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId");

                    b.ToTable("BelgeDosya", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.CariHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "CariKartId", "Tarih");

                    b.ToTable("CariHareket", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.CariKart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNoTc")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Unvan");

                    b.HasIndex("IsletmeId", "VergiNoTc");

                    b.ToTable("CariKart", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.DesktopImportCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClaimedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImportedTotalsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PackageId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int?>("TargetIsletmeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("TargetIsletmeId");

                    b.HasIndex("RequestedBy", "Status", "ExpiresAtUtc");

                    b.ToTable("DesktopImportCode", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<decimal>("AraToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FaturaTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GenelToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("HizliSatisAnahtari")
                        .HasColumnType("text");

                    b.Property<decimal>("IskontoToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime?>("KesildiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("OdenenTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("PortalBelgeNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PortalUuid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("VadeTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YerelFaturaNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "CariKartId");

                    b.HasIndex("IsletmeId", "HizliSatisAnahtari")
                        .IsUnique();

                    b.HasIndex("IsletmeId", "Tarih");

                    b.HasIndex("IsletmeId", "FaturaTipi", "Durum", "VadeTarihi");

                    b.ToTable("Fatura", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.FaturaSatir", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("BirimFiyat")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<decimal>("IskontoOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("IskontoTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("KdvTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("SatirNetTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("SatirToplam")
                        .HasColumnType("NUMERIC");

                    b.Property<bool>("StokEtkilesin")
                        .HasColumnType("boolean");

                    b.Property<int?>("UrunHizmetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId");

                    b.ToTable("FaturaSatir", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.GibPortalAyar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("KullaniciKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreCipherText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TestModu")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId")
                        .IsUnique();

                    b.ToTable("GibPortalAyar", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.GibPortalIslemLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Basarili")
                        .HasColumnType("boolean");

                    b.Property<int?>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId", "Tarih");

                    b.ToTable("GibPortalIslemLog", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Isletme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClerkOrganizationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsAktif")
                        .HasColumnType("boolean");

                    b.Property<string>("IsletmeTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("KolayKurulumTamamlandi")
                        .HasColumnType("boolean");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("MuhasebeciVarMi")
                        .HasColumnType("boolean");

                    b.Property<int?>("SahipKullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("TenantTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClerkOrganizationId")
                        .IsUnique();

                    b.HasIndex("IsAktif");

                    b.HasIndex("IsletmeTuru");

                    b.HasIndex("MuhasebeciVarMi");

                    b.HasIndex("SahipKullaniciId");

                    b.HasIndex("TenantTipi");

                    b.ToTable("Isletme", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.IsletmeDeneme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("BitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("DonemSonundaIptal")
                        .HasColumnType("boolean");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EkMusteriKredisi")
                        .HasColumnType("integer");

                    b.Property<string>("FaturalamaDonemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IptalAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeSaglayici")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("OdemeYontemiEklendi")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciMusteriId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciOdemeYontemiId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UcGunHatirlatmaAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("YediGunHatirlatmaAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "HesapTipi")
                        .IsUnique();

                    b.ToTable("IsletmeDeneme", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.IsletmeEntitlement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AiAktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("AiMesajLimiti")
                        .HasColumnType("integer");

                    b.Property<bool>("DonemOtomasyonuAktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("GecerliBaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("GecerliBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("GibAktif")
                        .HasColumnType("boolean");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("KullaniciLimiti")
                        .HasColumnType("integer");

                    b.Property<bool>("MuhasebeciPaneliAktif")
                        .HasColumnType("boolean");

                    b.Property<int?>("MusteriLimiti")
                        .HasColumnType("integer");

                    b.Property<bool>("MusteriSaglikSkoruAktif")
                        .HasColumnType("boolean");

                    b.Property<bool>("OcrAktif")
                        .HasColumnType("boolean");

                    b.Property<bool>("OneCikmaAktif")
                        .HasColumnType("boolean");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("SponsorMuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<bool>("TelegramAktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId")
                        .IsUnique();

                    b.HasIndex("Kaynak");

                    b.HasIndex("PlanKodu");

                    b.HasIndex("SponsorMuhasebeciIsletmeId");

                    b.ToTable("IsletmeEntitlement", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.IsletmeUyelik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DavetAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("DavetEdenKullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("DavetEposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DavetKodu")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("KabulAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("integer");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("DavetKodu")
                        .IsUnique();

                    b.HasIndex("IsletmeId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("IsletmeId", "KullaniciId")
                        .IsUnique();

                    b.ToTable("IsletmeUyelik", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.KalemTanimi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Tip", "Ad")
                        .IsUnique();

                    b.ToTable("KalemTanimi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Kasa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GiderTuru")
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kalem")
                        .HasColumnType("text");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Tarih");

                    b.ToTable("Kasa", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AuthProviderUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonGirisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Eposta");

                    b.HasIndex("HesapTipi");

                    b.HasIndex("AuthProvider", "AuthProviderUserId")
                        .IsUnique();

                    b.ToTable("Kullanici", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.KurucuKampanyaHakki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckoutAnahtari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("KampanyaKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("KazanildiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RezervasyonBitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("RezerveAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SiraNo")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutAnahtari")
                        .IsUnique();

                    b.HasIndex("KampanyaKodu", "IsletmeId")
                        .IsUnique();

                    b.HasIndex("KampanyaKodu", "SiraNo")
                        .IsUnique();

                    b.HasIndex("KampanyaKodu", "Durum", "RezervasyonBitisAt");

                    b.ToTable("KurucuKampanyaHakki", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciMusteri", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BaslangicAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BitisAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DavetKodu")
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("KabulAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("MusteriIsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Notlar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("TalepId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YetkiSeviyesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DavetKodu")
                        .IsUnique();

                    b.HasIndex("MuhasebeciIsletmeId");

                    b.HasIndex("MusteriIsletmeId");

                    b.HasIndex("TalepId");

                    b.HasIndex("YetkiSeviyesi");

                    b.HasIndex("MuhasebeciIsletmeId", "MusteriIsletmeId")
                        .IsUnique();

                    b.ToTable("MuhasebeciMusteri", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciMusteriTalebi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DavetKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<int?>("MusteriIsletmeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SonucAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TalepEdenIsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Tur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("YetkiSeviyesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DavetKodu");

                    b.HasIndex("Durum");

                    b.HasIndex("MuhasebeciIsletmeId");

                    b.HasIndex("MusteriIsletmeId");

                    b.HasIndex("TalepEdenIsletmeId");

                    b.HasIndex("MuhasebeciIsletmeId", "MusteriIsletmeId", "Durum");

                    b.ToTable("MuhasebeciMusteriTalebi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciProfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("DeneyimYili")
                        .HasColumnType("integer");

                    b.Property<string>("KisaAciklama")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Konum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("MusteriTipleri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilResmiUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UcretBilgisi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Uzmanliklar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Yayinda")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("DeneyimYili");

                    b.HasIndex("Konum");

                    b.HasIndex("MuhasebeciIsletmeId")
                        .IsUnique();

                    b.HasIndex("Yayinda");

                    b.ToTable("MuhasebeciProfil", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciSohbet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaglantiId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("MusteriIsletmeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SonMesajAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("TalepId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("BaglantiId");

                    b.HasIndex("MuhasebeciIsletmeId");

                    b.HasIndex("MusteriIsletmeId");

                    b.HasIndex("SonMesajAt");

                    b.HasIndex("TalepId");

                    b.HasIndex("MuhasebeciIsletmeId", "MusteriIsletmeId")
                        .IsUnique();

                    b.ToTable("MuhasebeciSohbet", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciSohbetEki", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Boyut")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DosyaAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DosyaYolu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EkTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IcerikTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MesajId")
                        .HasColumnType("integer");

                    b.Property<string>("OzetJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SohbetId")
                        .HasColumnType("integer");

                    b.Property<string>("VeriTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("YukleyenIsletmeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EkTipi");

                    b.HasIndex("MesajId");

                    b.HasIndex("SohbetId");

                    b.HasIndex("YukleyenIsletmeId");

                    b.ToTable("MuhasebeciSohbetEki", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciSohbetKatilimciDurumu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Arsivlendi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ArsivlendiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("SohbetId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("SonOkumaAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Arsivlendi");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("SohbetId");

                    b.HasIndex("SohbetId", "IsletmeId")
                        .IsUnique();

                    b.ToTable("MuhasebeciSohbetKatilimciDurumu", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciSohbetMesaji", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaglantiId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientMessageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("GonderenIsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MesajTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("MuhasebeciIsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("MusteriIsletmeId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("OkunduAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SohbetId")
                        .HasColumnType("integer");

                    b.Property<int?>("TalepId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BaglantiId");

                    b.HasIndex("MuhasebeciIsletmeId");

                    b.HasIndex("MusteriIsletmeId");

                    b.HasIndex("OkunduAt");

                    b.HasIndex("SohbetId");

                    b.HasIndex("TalepId");

                    b.HasIndex("SohbetId", "ClientMessageId");

                    b.HasIndex("SohbetId", "Id");

                    b.HasIndex("MuhasebeciIsletmeId", "MusteriIsletmeId", "CreatedAt");

                    b.ToTable("MuhasebeciSohbetMesaji", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.MuhasebeciSohbetVeriIstegi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AralikKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Baslangic")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Bitis")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("HedefIsletmeId")
                        .HasColumnType("integer");

                    b.Property<int>("IsteyenIsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Mesaj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SohbetId")
                        .HasColumnType("integer");

                    b.Property<int?>("SonucEkId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("VeriTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Durum");

                    b.HasIndex("HedefIsletmeId");

                    b.HasIndex("IsteyenIsletmeId");

                    b.HasIndex("SohbetId");

                    b.ToTable("MuhasebeciSohbetVeriIstegi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.NakitPlanKalemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("IlkTarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<int>("TekrarAraligi")
                        .HasColumnType("integer");

                    b.Property<string>("TekrarTipi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Aktif", "IlkTarih");

                    b.ToTable("NakitPlanKalemi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.OdemeHatirlatma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AliciEposta")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)");

                    b.Property<int>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GonderildiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Hata")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Konu")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("character varying(240)");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId", "GonderildiAt");

                    b.ToTable("OdemeHatirlatma", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.OdemeIslemi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CheckoutAnahtari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CheckoutExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CheckoutUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EkMusteriKredisi")
                        .HasColumnType("integer");

                    b.Property<string>("FaturalamaDonemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HataKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HataMesaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HesapTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IndirimliDonemSayisi")
                        .HasColumnType("integer");

                    b.Property<string>("IslemTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("KampanyaKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("KdvTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("ListeNetTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("NetTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("OdemeSaglayici")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ParaBirimi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PlanKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciIslemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SaglayiciOturumId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SonOlayAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("TamamlandiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("ToplamTutar")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("YenilemeNetTutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("SaglayiciIslemId");

                    b.HasIndex("SaglayiciOturumId");

                    b.HasIndex("IsletmeId", "CheckoutAnahtari")
                        .IsUnique();

                    b.ToTable("OdemeIslemi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.OdemeOlayi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AlindiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CheckoutAnahtari")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HataMesaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("IslendiAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("IslenmeDurumu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OdemeSaglayici")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OlayId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OlayTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SaglayiciAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SaglayiciIslemId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CheckoutAnahtari");

                    b.HasIndex("SaglayiciIslemId");

                    b.HasIndex("OdemeSaglayici", "OlayId")
                        .IsUnique();

                    b.ToTable("OdemeOlayi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.StokHareket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("Kaynak")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Miktar")
                        .HasColumnType("NUMERIC");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("UrunHizmetId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "UrunHizmetId", "Tarih");

                    b.ToTable("StokHareket", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.TahsilatOdeme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Aciklama")
                        .HasColumnType("text");

                    b.Property<int?>("CariHareketId")
                        .HasColumnType("integer");

                    b.Property<int>("CariKartId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("FaturaId")
                        .HasColumnType("integer");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<int?>("KasaId")
                        .HasColumnType("integer");

                    b.Property<string>("OdemeYontemi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("NUMERIC");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "FaturaId");

                    b.HasIndex("IsletmeId", "CariKartId", "Tarih");

                    b.HasIndex("IsletmeId", "FaturaId", "Tarih");

                    b.ToTable("TahsilatOdeme", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.UrunHizmet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Aktif")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AlisFiyati")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("Barkod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Birim")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("KdvOrani")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("KritikStok")
                        .HasColumnType("NUMERIC");

                    b.Property<decimal>("SatisFiyati")
                        .HasColumnType("NUMERIC");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsletmeId");

                    b.HasIndex("IsletmeId", "Barkod");

                    b.ToTable("UrunHizmet", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.YonetimDenetimKaydi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AktorProviderKullaniciId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Gerekce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Islem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("IsletmeId")
                        .HasColumnType("integer");

                    b.Property<string>("KaynakTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OncekiDeger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YeniDeger")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsletmeId");

                    b.ToTable("YonetimDenetimKaydi", (string)null);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.DesktopImportCode", b =>
                {
                    b.HasOne("CashTracker.Core.Entities.Isletme", null)
                        .WithMany()
                        .HasForeignKey("TargetIsletmeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CashTracker.Core.Entities.NakitPlanKalemi", b =>
                {
                    b.HasOne("CashTracker.Core.Entities.Isletme", null)
                        .WithMany()
                        .HasForeignKey("IsletmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
